version: "3.9"
services:
  web_crawler:
    container_name: web_crawler
    image: web_crawler
    build: web_crawler
    restart: always
  nginx:
    container_name: nginx
    image: nginx:1.23-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web_crawler
